name: ansible-lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gity Repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: |
            **/requirements*.txt
            /dev/null
          python-version: "3.11"
          
      - name: Install ansible-lint
        shell: bash
        run: pip install ansible-lint
        
      - name: Run ansible-lint on playbooks
        shell: bash
        run: ansible-lint ${{ inputs.path }}
